
// src/lib/tldraw-fr.ts
"use client"

import { useDefaultTranslation } from '@tldraw/tldraw'

// This file is mostly AI-generated, and may have mistakes.
// If you see any, please file an issue on GitHub.
const TLDRAW_FRENCH_TRANSLATION = {
	"action.bring-forward": "Avancer",
	"action.bring-to-front": "Amener au premier plan",
	"action.copy": "Copier",
	"action.copy-as-embed": "Copier l'intégration",
	"action.copy-as-json": "Copier en JSON",
	"action.copy-as-png": "Copier en PNG",
	"action.copy-as-svg": "Copier en SVG",
	"action.cut": "Couper",
	"action.delete": "Supprimer",
	"action.duplicate": "Dupliquer",
	"action.edit-link": "Modifier le lien",
	"action.export-as-embed": "Exporter en tant qu'intégration",
	"action.export-as-json": "Exporter en JSON",
	"action.export-as-png": "Exporter en PNG",
	"action.export-as-svg": "Exporter en SVG",
	"action.flip-horizontal": "Retourner horizontalement",
	"action.flip-vertical": "Retourner verticalement",
	"action.fork-project-on-tldraw": "Dupliquer sur tldraw.com",
	"action.group": "Grouper",
	"action.move-down": "Déplacer vers le bas",
	"action.move-to-page": "Déplacer vers la page",
	"action.move-up": "Déplacer vers le haut",
	"action.open-embed-link": "Ouvrir le lien de l'intégration",
	"action.pack": "Compresser",
	"action.paste": "Coller",
	"action.print": "Imprimer",
	"action.redo": "Refaire",
	"action.reorder.bring-forward": "Avancer",
	"action.reorder.bring-to-front": "Amener au premier plan",
	"action.reorder.send-backward": "Reculer",
	"action.reorder.send-to-back": "Mettre en arrière-plan",
	"action.rotate-cw": "Rotation horaire",
	"action.rotate-acw": "Rotation anti-horaire",
	"action.select-all": "Sélectionner tout",
	"action.select-none": "Ne rien sélectionner",
	"action.send-backward": "Reculer",
	"action.send-to-back": "Mettre en arrière-plan",
	"action.toggle-dark-mode": "Activer le mode sombre",
	"action.toggle-focus-mode": "Activer le mode focus",
	"action.toggle-grid": "Activer la grille",
	"action.toggle-transparent": "Rendre transparent",
	"action.undo": "Annuler",
	"action.ungroup": "Dégrouper",
	"action.zoom-in": "Zoomer",
	"action.zoom-out": "Dézoomer",
	"action.zoom-to-100": "Zoom à 100%",
	"action.zoom-to-fit": "Zoom pour ajuster",
	"action.zoom-to-selection": "Zoom sur la sélection",
	"aria.color-picker.blue": "Bleu",
	"aria.color-picker.green": "Vert",
	"aria.color-picker.grey": "Gris",
	"aria.color-picker.light-blue": "Bleu clair",
	"aria.color-picker.light-green": "Vert clair",
	"aria.color-picker.light-red": "Rouge clair",
	"aria.color-picker.light-violet": "Violet clair",
	"aria.color-picker.orange": "Orange",
	"aria.color-picker.red": "Rouge",
	"aria.color-picker.violet": "Violet",
	"aria.color-picker.yellow": "Jaune",
	"aria.color-input.storage-key": "Clé de stockage pour la couleur",
	"aria.color-input.tooltip": "Choisir une couleur",
	"aria.help-menu.title": "Menu d'aide",
	"aria.main-menu.title": "Menu principal",
	"aria.page-menu.title": "Menu de la page",
	"aria.share-menu.title": "Menu de partage",
	"aria.style-panel.title": "Panneau de style",
	"aria.tool-panel.title": "Panneau d'outils",
	"aria.zoom-menu.title": "Menu de zoom",
	"color-style.black": "Noir",
	"color-style.blue": "Bleu",
	"color-style.green": "Vert",
	"color-style.grey": "Gris",
	"color-style.light-blue": "Bleu clair",
	"color-style.light-green": "Vert clair",
	"color-style.light-red": "Rouge clair",
	"color-style.light-violet": "Violet clair",
	"color-style.orange": "Orange",
	"color-style.red": "Rouge",
	"color-style.violet": "Violet",
	"color-style.white": "Blanc",
	"color-style.yellow": "Jaune",
	"dash-style.dashed": "Tirets",
	"dash-style.dotted": "Points",
	"dash-style.draw": "Dessin",
	"dash-style.solid": "Solide",
	"embed-dialog.cancel": "Annuler",
	"embed-dialog.create": "Créer",
	"embed-dialog.title": "Intégrer",
	"embed-dialog.url": "URL",
	"fill-style.hachure": "Hachure",
	"fill-style.none": "Aucun",
	"fill-style.semi": "Semi",
	"fill-style.solid": "Solide",
	"font-style.draw": "Dessin",
	"font-style.mono": "Mono",
	"font-style.sans": "Sans",
	"font-style.serif": "Serif",
	"font-style.script": "Script",
	"help-menu.community": "Communauté",
	"help-menu.discord": "Discord",
	"help-menu.github": "GitHub",
	"help-menu.keyboard-shortcuts": "Raccourcis clavier",
	"help-menu.twitter": "Twitter",
	"help-menu.language": "Langue",
	"main-menu.about-tldraw": "À propos de tldraw",
	"main-menu.account": "Compte",
	"main-menu.check-for-updates": "Vérifier les mises à jour",
	"main-menu.create-new-project": "Créer un nouveau projet",
	"main-menu.edit": "Modifier",
	"main-menu.export-as": "Exporter en tant que...",
	"main-menu.file": "Fichier",
	"main-menu.help": "Aide",
	"main-menu.open-recent": "Ouvrir récent",
	"main-menu.sign-in": "Se connecter",
	"main-menu.sign-out": "Se déconnecter",
	"main-menu.view": "Vue",
	"page-menu.create-new-page": "Créer une nouvelle page",
	"page-menu.delete-page": "Supprimer la page",
	"page-menu.duplicate-page": "Dupliquer la page",
	"page-menu.edit-page-name": "Modifier le nom de la page",
	"share-menu.copy-link-to-project": "Copier le lien du projet",
	"share-menu.start-a-multiplayer-session": "Démarrer une session multijoueur",
	"share-menu.stop-a-multiplayer-session": "Arrêter la session multijoueur",
	"size-style.l": "Grande",
	"size-style.m": "Moyenne",
	"size-style.s": "Petite",
	"size-style.xl": "Très Grande",
	"tool.arrow": "Flèche",
	"tool.cloud": "Nuage",
	"tool.draw": "Dessin",
	"tool.ellipse": "Ellipse",
	"tool.embed": "Intégration",
	"tool.eraser": "Gomme",
	"tool.frame": "Cadre",
	"tool.hand": "Main",
	"tool.hexagon": "Hexagone",
	"tool.highlight": "Surligneur",
	"tool.line": "Ligne",
	"tool.note": "Note",
	"tool.octagon": "Octogone",
	"tool.oval": "Ovale",
	"tool.pentagon": "Pentagone",
	"tool.rectangle": "Rectangle",
	"tool.rhombus": "Losange",
	"tool.select": "Sélectionner",
	"tool.star": "Étoile",
	"tool.text": "Texte",
	"tool.trapezoid": "Trapèze",
	"tool.triangle": "Triangle",
	"tool-panel.align-bottom": "Aligner en bas",
	"tool-panel.align-center-horizontal": "Aligner au centre horizontalement",
	"tool-panel.align-center-vertical": "Aligner au centre verticalement",
	"tool-panel.align-left": "Aligner à gauche",
	"tool-panel.align-right": "Aligner à droite",
	"tool-panel.align-top": "Aligner en haut",
	"tool-panel.distribute-horizontal": "Distribuer horizontalement",
	"tool-panel.distribute-vertical": "Distribuer verticalement",
	"tool-panel.flip-horizontal": "Retourner horizontalement",
	"tool-panel.flip-vertical": "Retourner verticalement",
	"tool-panel.lock-aspect-ratio": "Conserver le rapport d'aspect",
	"tool-panel.pack": "Compresser",
	"tool-panel.stack-horizontal": "Empiler horizontalement",
	"tool-panel.stack-vertical": "Empiler verticalement",
	"tool-panel.stretch-horizontal": "Étendre horizontalement",
	"tool-panel.stretch-vertical": "Étendre verticalement",
	"tool-panel.unlock-aspect-ratio": "Déverrouiller le rapport d'aspect",
	"style.align": "Alignement",
	"style.align.center": "Centre",
	"style.align.end": "Fin",
	"style.align.justify": "Justifier",
	"style.align.left": "Gauche",
	"style.align.middle": "Milieu",
	"style.align.right": "Droite",
	"style.align.start": "Début",
	"style.color": "Couleur",
	"style.dash": "Tiret",
	"style.fill": "Remplissage",
	"style.font": "Police",
	"style.size": "Taille",
	"style.horizontal-align": "Alignement horizontal",
	"style.vertical-align": "Alignement vertical",
	"styles-panel.title": "Styles",
	"toast.error.copy-fail-generic": "Échec de la copie",
	"toast.error.copy-fail-must-be-https": "La connexion doit être sécurisée pour copier le lien.",
	"toast.error.export-fail-generic": "Échec de l'exportation",
	"toast.error.paste-fail-generic": "Échec du collage",
	"toast.error.paste-fail-image": "Impossible de coller les images.",
	"toast.error.paste-fail-max-size": "Le fichier est trop volumineux.",
	"toast.error.paste-fail-unexpected-type": "Type de fichier inattendu.",
	"toast.info.clipboard-permission-denied": "Veuillez autoriser l'accès au presse-papiers pour utiliser cette fonctionnalité.",
	"zoom-menu.reset-zoom": "Réinitialiser le zoom",
	"zoom-menu.zoom-in": "Zoomer",
	"zoom-menu.zoom-out": "Dézoomer",
	"zoom-menu.zoom-to-fit": "Zoom pour ajuster",
	"zoom-menu.zoom-to-selection": "Zoom sur la sélection",
}
export function FrenchTranslation() {
	useDefaultTranslation(TLDRAW_FRENCH_TRANSLATION)
	return null
}
