// src/lib/tldraw-fr.ts
"use client"

import { useTranslation } from '@tldraw/tldraw'

const TRANSLATION = {
	"action.bring-forward": "Avancer",
	"action.bring-to-front": "Amener au premier plan",
	"action.copy": "Copier",
	"action.copy-as-embed": "Copier l'intégration",
	"action.copy-as-json": "Copier en JSON",
	"action.copy-as-png": "Copier en PNG",
	"action.copy-as-svg": "Copier en SVG",
alue: "Valeur",
	"style.vertical-align": "Alignement vertical",
	"style.vertical-align.end": "Bas",
	"style.vertical-align.middle": "Milieu",
	"style.vertical-align.start": "Haut",
	"tool.arrow": "Flèche",
	"tool.draw": "Dessin",
	"tool.ellipse": "Ellipse",
	"tool.embed": "Intégration",
	"tool.eraser": "Gomme",
	"tool.frame": "Cadre",
	"tool.hand": "Main",
	"tool.highlight": "Surligneur",
	"tool.laser": "Laser",
	"tool.line": "Ligne",
	"tool.note": "Note",
	"tool.rectangle": "Rectangle",
	"tool.select": "Sélectionner",
	"tool.text": "Texte",
	"tool-group.shapes": "Formes",
	"tool-group.tools": "Outils",
	"tool.triangle": "Triangle",
	"tool-panel.lock-aspect-ratio": "Conserver le rapport d'aspect",
	"tool-panel.unlock-aspect-ratio": "Ne pas conserver le rapport d'aspect",
	"tool.geo": "Forme géométrique",
	"tool.rhombus": "Losange",
	"tool.oval": "Ovale",
	"tool.trapezoid": "Trapèze",
	"tool.star": "Étoile",
	"tool.cloud": "Nuage",
	"tool.hexagon": "Hexagone",
	"tool.pentagon": "Pentagone",
	"tool.octagon": "Octogone",
	"tool.check-box": "Case à cocher",
	"tool-panel.align-bottom": "Aligner en bas",
	"tool-panel.align-center-horizontal": "Aligner au centre horizontalement",
	"tool-panel.align-center-vertical": "Aligner au centre verticalement",
	"tool-panel.align-left": "Aligner à gauche",
	"tool-panel.align-right": "Aligner à droite",
	"tool-panel.align-top": "Aligner en haut",
	"tool-panel.distribute-horizontal": "Distribuer horizontalement",
	"tool-panel.distribute-vertical": "Distribuer verticalement",
	"tool-panel.stretch-horizontal": "Étendre horizontalement",
	"tool-panel.stretch-vertical": "Étendre verticalement",
	"tool-panel.flip-horizontal": "Retourner horizontalement",
	"tool-panel.flip-vertical": "Retourner verticalement",
	"tool-panel.pack": "Compresser",
	"tool-panel.stack-horizontal": "Empiler horizontalement",
	"tool-panel.stack-vertical": "Empiler verticalement",
	"tool.asset": "Média",
	"dialog.menu.preferences": "Préférences",
	"dialog.preferences.dark-mode": "Mode sombre",
	"dialog.preferences.focus-mode": "Mode focus",
	"dialog.preferences.debug-mode": "Mode débogage",
	"dialog.preferences.show-grid": "Afficher la grille",
	"dialog.preferences.use-animation": "Utiliser l'animation",
	"dialog.preferences.always-show-snaps": "Toujours afficher les points d'accroche",
	"dialog.preferences.rotate-handles": "Poignées de rotation",
	"dialog.preferences.binding-handles": "Poignées de liaison",
	"dialog.preferences.clone-handles": "Poignées de clonage",
	"dialog.preferences.author-strip": "Bandeau de l'auteur",
	"dialog.preferences.edge-scrolling": "Défilement sur les bords",
	"dialog.preferences.language": "Langue",
	"dialog.preferences.color-theme": "Thème de couleur",
	"page-menu.title": "Page",
	"page-menu.new-page": "Nouvelle page",
	"page-menu.rename-page": "Renommer la page",
	"page-menu.duplicate-page": "Dupliquer la page",
	"page-menu.delete-page": "Supprimer la page"
}

export function FrenchTranslation() {
	useTranslation(TRANSLATION)
	return null
}
